<a href="https://colab.research.google.com/github/cagBRT/Machine-Learning/blob/master/KNN3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using the KNeighbors algorithm from SKLearn, experiment with different dataset sizes, number of features, and number of neighbors. <br>
The notebook will produce the confusion matrix for both the uniform and the distance versions of the algorithm. 

In [10]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from random import seed
from random import random
from random import randint
from sklearn.neighbors import KNeighborsClassifier

**Set the number of neighbors to vote**

In [11]:
n_neighbors = 5 #change 

**Get and prepare the data**

In [12]:
from sklearn.datasets import make_classification
# Generate Balanced Data
X,y = make_classification(n_samples=50, n_features=2, 
                          n_redundant=0, n_repeated=0, n_classes=3, 
                          n_clusters_per_class=1,class_sep=2,
                          flip_y=0,weights=[0.33,0.33,0.33], 
                          random_state=randint(0,20))

In [13]:
X.shape

(50, 2)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

**Do classification for both uniform and distance weights**<br>
>‘uniform’ : uniform weights. All points in each neighborhood are weighted equally.

>‘distance’ : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.

In [15]:
clf_U = neighbors.KNeighborsClassifier(n_neighbors, weights='uniform')
U_trained=clf_U.fit(X_train, y_train)
y_U_pred = clf_U.predict(X_test)


In [17]:
clf_D = neighbors.KNeighborsClassifier(n_neighbors, weights='distance')
D_trained =clf_D.fit(X_train, y_train)
y_D_pred = clf_D.predict(X_test)

**Create a confusion matrix and classification report for each of the weights**

In [19]:
print("clf_U model")
print(confusion_matrix(y_test, y_U_pred))
print(classification_report(y_test, y_U_pred))

print("clf_D model")
print(confusion_matrix(y_test, y_D_pred))
print(classification_report(y_test, y_D_pred))

clf_U model
[[4 0 0]
 [0 7 0]
 [0 0 6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         6

    accuracy                           1.00        17
   macro avg       1.00      1.00      1.00        17
weighted avg       1.00      1.00      1.00        17

clf_D model
[[4 0 0]
 [0 7 0]
 [0 0 6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         6

    accuracy                           1.00        17
   macro avg       1.00      1.00      1.00        17
weighted avg       1.00      1.00      1.00        17



**Assignment** <br>
1. Change the number of neighbors and see the effect, if any,  on the confusion matrices. 
2. Try different dataset sizes. How does the algorithm perform?
3. Change the number of features. Start with 2 then progress up to 40. How does the alogrithm perform?
4. Change class_sep=1 in the dataset. How does the algorithm perform when the classes are closer together?
